### ISSUE TITLE
Need some advice

### ISSUE THREAD

**Issue by 1703879E** [1703879E/T05-SWEN#1]
What should our app design for the general homepage look like? Is this ok?
[login.component.zip](https://github.com/1703879E/T05-SWEN/files/2847899/login.component.zip)

**Comment by BorkerDorker** [comment]
yo, thats pretty dope my dude. 
sick work as always
keep the good work going

**Comment by Zero716** [comment]
Hmmmm it looks okay. Ya sure just leave it as liddat

**Comment by 1703879E** [comment]
Thanks guys I appreciate it!

**Comment by Zero716** [comment]
np
